### ISSUE TITLE
请教一个关于B站动态页脚本开发的问题

### ISSUE THREAD

**Issue by Jingle-seven** [liangjiancang/userscript#2]
作者你好，我一直有在用你的稍后再看增强脚本，最近想自己写一个运行于B站动态页 https://t.bilibili.com/  的脚本，但是发现刷新页面时脚本会运行两次，如同这个脚本一样[Bilibili AntiBV](https://greasyfork.org/zh-CN/scripts/398499-bilibili-antibv)，但是稍后再看增强脚本就没有加载两次的问题，所以想请教一下，怎么避免油猴脚本在B站动态页加载两次？

**Comment by liangjiancang** [comment]
那是因为脚本被注入到 `iframe` 中，要避免这一点可以使用 [@noframes](https://www.tampermonkey.net/documentation.php#_noframes) 标签（Tampermonkey 用户可通过「仅在顶层页面（框架）运行」覆盖脚本的注入范围设置）。

对于那些需要注入到 `iframe` 中而不能使用 `@noframes` 的脚本：
1. 使用 `self === top` 来判断脚本是否运行在顶层，根据需要终止运行，缺点是终究是在 `iframe` 中生成了脚本实例。
2. 找出脚本会在哪些 `iframe` 中运行，然后通过 `@exclude` 排除掉。

具体参考一下 [B站特殊页面](https://github.com/liangjiancang/userscript/blob/master/doc/B%E7%AB%99%E7%89%B9%E6%AE%8A%E9%A1%B5%E9%9D%A2.md)。

**Comment by Jingle-seven** [comment]
非常感谢，问题解决了~
